modLoader = "javafml" #mandatory
loaderVersion = "[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "All rights reserved"
issueTrackerURL = "https://github.com/manmaed/cottonly/issues" #optional
[[mods]] #mandatory
modId = "cottonly" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Cottonly" #mandatory
updateJSONURL = "https://raw.githubusercontent.com/manmaed/cottonly/main/update.json"
authors = "manmaed" #optional
logoFile = "cotton_logo.png"
description = '''
Cotton Plant'''