modLoader = "javafml"
loaderVersion = "[1,)"
license = "All rights reserved"
issueTrackerURL = "https://github.com/manmaed/cottonly/issues"
[[mods]]
modId = "cottonly"
version="${version}"
displayName = "Cottonly"
updateJSONURL = "https://raw.githubusercontent.com/manmaed/cottonly/main/neo-update.json"
authors = "manmaed"
logoFile = "cotton_logo.png"
description = '''Cotton Plant'''
[[dependencies.cottonly]]
modId="neoforge"
mandatory=true
versionRange="[21.0.113-beta,)"
ordering="NONE"
side="BOTH"