name: Build & Release to 1.16.5

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[skip]')
    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/checkout@v2
      - name: Set up Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      - name: Build & release to curseforge
        env:
          CURSE_DEPLOY: ${{ secrets.CURSE_DEPLOY }}
        run: |
          chmod +x ./gradlew
          ./gradlew build publish curseforge --stacktrace --no-daemon