name: Build & Release For Minecraft 1.16.5 

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Build & release to curseforge
        env:
          CURSE_DEPLOY: ${{ secrets.CURSE_DEPLOY }}
        run: |
          chmod +x ./gradlew
          ./gradlew build curseforge --stacktrace --no-daemon